### ISSUE TITLE
New "YAML" Configuration

### ISSUE THREAD

**Issue by Ryuinferno** [crowdin/crowdin-cli#22]
Just wondering why JSON is preferred instead of YAML like previously? The current configuration format is not in YAML (hence it should not be called as "new YAML format"),  which can be quite troublesome since anchoring and referencing cannot be done anymore (see https://github.com/Ryuinferno/mk_crowdin/blob/kk_mkt/crowdin/crowdin_mk.yaml for an example). Thank you!

**Comment by ihor-popyk** [comment]
Hello @Ryuinferno ! Thank you for your question.
First of all, I wish to inform you that the "old format" is also supported in СLI 2. We preferred  JSON format because it is easier to use.
But, you also can use anchors and references in "new" JSON format. Please, try my example for you: https://gist.github.com/ihor-popyk/0b170c0261ce0cc23b0c6732232164f0
Please notify me if it's works for you

**Comment by ShawnTeoh** [comment]
Thank you so much for informing! I tried it and verified using the "lint" option, no errors reported. However, I am unable to perform a proper test run since the cli hangs after building the translations. I have 42 files to translate (scattered around 500++ directories, each with different numbers of sub-directories).

The command I tried was: `crowdin download -b branch --config crowdin.yml`

**Comment by Ryuinferno** [comment]
Thank you so much for informing! I tried it and verified using the "lint" option, no errors reported. However, I am unable to perform a proper test run since the cli hangs after building the translations. I have 42 files to translate (scattered around 500++ directories, each with different numbers of sub-directories).

The command I tried was: `crowdin download -b branch --config crowdin.yml`

**Comment by ihor-popyk** [comment]
If you have many files and they are translated to many languages, the project needs a lot of time to build. To check if CLI really hangs, please run "download" command again and check the status of build in web ui, in project settings in translation tab or in API tab (API log). If this does not help, write your project credentials me directly or via our Customer Success Service (https://crowdin.com/contacts).
Waiting for your answer.

**Comment by Ryuinferno** [comment]
Thank you, I have submitted my issue through https://crowdin.com/contacts

**Comment by ihor-popyk** [comment]
Hello @Ryuinferno 
Can you confirm whether your problem is solved?

**Comment by Ryuinferno** [comment]
Unfortunately no, and I have not received any follow up after reporting. I believe that the issue we faced is related to https://github.com/crowdin/crowdin-cli-2/issues/39 since our setup is similar

**Comment by ihor-popyk** [comment]
So, sorry for that.
Made some improvements in #44. So 2.0.15 will be faster.
