### ISSUE TITLE
ENV variable in addition to alias for crowdin cli v3

### ISSUE THREAD

**Issue by yefrem** [crowdin/crowdin-cli#249]
We have a wrapper around Crowdin CLI and there's a small issue with migrating to v3. It relies on alias which is not available from bash script. 
As a workaround we have to do
```
shopt -s expand_aliases
source ~/.bashrc
```
But it doesn't feel clean enough.
What about adding ENV var together with alias, like 
`export CROWDIN_COMMAND="java -jar /usr/local/bin/crowdin-cli.jar"`?

**Comment by andrii-bodnar** [comment]
Hi, @yefrem !
I'm not sure I understand you correctly, can you explain in more detail? How can it be implemented in CLI and what's the difference between v2 and v3 in this case?

**Comment by yefrem** [comment]
Hello, thanks for the quick reply. Yeah, I guess I didn't explain it well. The issue is in cli installer. V2 installer creates standalone executable file and v3 creates add alias to .bashrc and .bash_profile. The difference is that when we try calling crowdin cli from another bash script, alias is not immediately available there and requires a hack mentioned above (allow aliases then include .bashrc manually). 
The solution I suggest is creating ENV var in addition to the alias as ENV should be correctly passed to the script.

**Comment by andrii-bodnar** [comment]
@yefrem thanks for the explanation. Are you using [Standalone Version](https://support.crowdin.com/cli-tool-v3/#standalone-version) installation via `install-crowdin-cli.sh` script?

**Comment by yefrem** [comment]
yes

**Comment by andrii-bodnar** [comment]
Great, we will consider adding the environment variable to this script. Thank you for the suggestion!

**Comment by cmrd-senya** [comment]
@andrii-bodnar is this repository the right place to ask about crowdin cli v3 installer issues? I have a few questions regarding it, but the installer doesn't seem to be included to the repository. Is there a better place?

**Comment by andrii-bodnar** [comment]
@cmrd-senya it's ok to ask in this repository :) 

How about to add installation scripts into the repository? Will it be useful for the contribution?

**Comment by cmrd-senya** [comment]
> How about to add installation scripts into the repository? Will it be useful for the contribution?

Yes, I think it would be useful

**Comment by andrii-bodnar** [comment]
@cmrd-senya , added - https://github.com/crowdin/crowdin-cli/pull/252

**Comment by cmrd-senya** [comment]
Awesome, thank you @andrii-bodnar!
I'll add a couple of bug reports for the installation script later today.

**Comment by cmrd-senya** [comment]
@andrii-bodnar, it's a bit out of scope for this issue, but, for your information:
I've created an AUR package for crowdin-cli v3: https://aur.archlinux.org/packages/crowdin-cli/

For me it resolves the issues I had with the provided installer: 
- it picks the available java version (including newer than 8)
- it doesn't use bash alias (it uses a shell script instead)
- it supports uninstallation (obviously, because it's a usual system package)

**Comment by andrii-bodnar** [comment]
@cmrd-senya, looks great, thank you! :thumbsup:

I think it will be very useful for users who need to install CLI on Arch Linux.

How to keep this package up to date?

**Comment by cmrd-senya** [comment]
@andrii-bodnar I'm still in process of figuring out the best way of maintaining the updates since it's my first AUR package and I'm not sure about what's better.
But in any case the update of the package would just require making some minimal changes (like version bump) to PKGBUILD file, veryfing the build is passing and pushing this change to AUR git. It shouldn't be very hard to integrate it to github CI pipeline to do this automatically for new releases.

**Comment by cmrd-senya** [comment]
@andrii-bodnar, so in order to update the package the following steps are required:
1. Bump package version to the latest git release tag
2. Run `makepkg` to make sure the build is passing
3. Update `.SRCINFO` by running `makepkg --printsrcinfo > .SRCINFO`
4. git commit && git push the changes to AUR

As long as there is no problems with the build after the update that's it.

I can update this package from time to time, but if you're interested in keeping an eye on it too, I can add you as a maintainer in AUR so that you had permission to push the update

**Comment by andrii-bodnar** [comment]
@cmrd-senya great!
Just registered account `crowdin` on aur.archlinux.org. 

Could you add it as maintainer? So we will be able to automate package updating in our CI/CD (it's separate CI/CD where already automated DEB, RPM, and ZIP publishing).

**Comment by cmrd-senya** [comment]
@andrii-bodnar I've added `crowdin` as a maintainer.

> So we will be able to automate package updating in our CI/CD (it's separate CI/CD where already automated DEB, RPM, and ZIP publishing).

Yes, it's possible. How do you build DEB/RPM packages? Do you use OS-specific docker images? Or you just build all the packages on the same system?

In order to update the package you'll need `makepkg` installed which is a part of pacman distribution. While it's possible to install it on a different system than Arch, it would be easier to just use Arch image for that.

**Comment by andrii-bodnar** [comment]
@cmrd-senya thanks! For DEB and RPM building we are using *ubuntu* and *rpmbuild/centos* images. I think it's easy to use the Arch image for AUR package building.

**Comment by cmrd-senya** [comment]
Just to clarify: with AUR you don't publish the built package. It's good to build it to make sure it's building without error before you push the changes, but you only push package build script source to AUR.

**Comment by cmrd-senya** [comment]
@andrii-bodnar this is very useful to read to learn about AUR publishing: https://wiki.archlinux.org/index.php/AUR_submission_guidelines

**Comment by andrii-bodnar** [comment]
@cmrd-senya thank you, it will be very useful, we'll definitely read this before publishing updates :slightly_smiling_face:

**Comment by cmrd-senya** [comment]
@andrii-bodnar feel free to contact me directly if you have any difficulties with this package. You can reach me by email (you can find it at AUR or in your project's git history). I can read and write Ukrainian and Russian language.

**Comment by cmrd-senya** [comment]
I think that given the recent installer changes this request is not relevant anymore for @yefrem and me.

@yefrem  can you confirm that?

**Comment by andrii-bodnar** [comment]
@cmrd-senya, I agree with you. 
@yefrem ? :)

**Comment by yefrem** [comment]
I don't mind closing it. Thanks.
