### ISSUE TITLE
[3.7.8] Working directory breaking change

### ISSUE THREAD

**Issue by Wohllebe-dotSource** [crowdin/crowdin-cli#439]
**Describe the bug**
Till version 3.7.7 the CLI tool downloads files into the working directory. Since 3.7.8 it ignores the working directory and force the use of the directory where the `crowdin.yaml` is located.

**To Reproduce**
1. `mkdir ~/project/src`
2. Create `~/project/crowdin.yml` with
```
"base_path": "./src"
"preserve_hierarchy": true
```
3. `mkdir /tmp/crowdin-test/src`
4. `cd /tmp/crowdin-test`
5. `crowdin download -c ~/project/crowdin.yml`

Files are located in `~/project/src` since 3.7.8.

**Expected behavior**
Files are located in `/tmp/crowdin-test/src` which was the default behavior till 3.7.7.

**Comment by barrerajl** [comment]
I am suffering the same breaking change.

**Comment by andrii-bodnar** [comment]
HI @Wohllebe-dotSource @barrerajl!

Before the 3.7.8 version, there was an unobvious and buggy behavior. Relative `base_path` (e.g. `./src` or `../src`) configured in the `crowdin.yml` was considered as relative not relating to the **configuration file**, but relating to the **current working directory**. `base_path` configured in the `crowdin.yml` config should be relative to the **config location**, not current directory.

In case you need a base path related to the current working directory, probably you need to use the `--base-path` command parameter instead of `base_path` in config. By the way, the command parameter has a higher priority than config `base_path`.

```
crowdin download -c ~/project/crowdin.yml --base-path "..."
```

**Comment by Wohllebe-dotSource** [comment]
Hi @andrii-bodnar,

thank you for the hint with the `--base-path` parameter. It works in my test when I set `--base-path` with my working directory + my relative `base_path` configuration from the `crowdin.yml`.

Unfortunately, it is a breaking change under a patch version. It would be nice if it's documented at least in the release notes with the corresponding workaround.

Thank you very much!

**Comment by andrii-bodnar** [comment]
@Wohllebe-dotSource happy to hear that using the command parameter works in your case. 

Sorry for the inconvenience. This is our fault, we did not anticipate and underestimated this change. We definitely should have released a minor version. 

We will add details to the release notes for this update.

**Comment by barrerajl** [comment]
@andrii-bodnar thanks for the update.
This is a breaking change for me, will try to use the command cli base path
